language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - npm install
#before_script:
 # - npm install -g gulp
script:
  - hexo generate
after_script:
  - cd ./public
  - git init
  - git config user.name "Dannyge"
  - git config user.email "gezhenying@gmail.com"
  - git add .
  - git commit -m "Update - auto deploy by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GITHUB_REF}" master:master
# E: Build LifeCycle
branches:
  only:
    - master
env:
  global:
    - GITHUB_REF: github.com/dannyge/dannyge.github.io.git