language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - npm install
#before_script:
 # - npm install -g gulp
script:
  - hexo generate
after_script:
  - sed -i "s/GH_TK/${GH_TK}/g" _config.yml
  - git config user.name "gezhenying@gmail.com"
  - hexo d
# E: Build LifeCycle
branches:
  only:
    - master