language: node_js
node_js: stable
# S: Build Lifecycle
install:
  - npm install
#before_script:
 # - npm install -g gulp
script:
  - hexo generate
after_script:
  - hexo d
# E: Build LifeCycle
branches:
  only:
    - master
